server:
  port: ${SERVER_PORT:8092}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:api-weather-service}
management:
  security:
    enabled: false

service:
   getHistoricUri: api/v1/weather/history/city/{city}/prediction/{prediction}
   getPredictionUri: api/v1/weather/{city}

dependencies:
   weatherServiceId: ${SERVICE_DEPENDECY_WEATHER:weather-service}
