server:
  port: 8092

spring:
  application:
    name: api-weather-service
management:
  security:
    enabled: false

service:
   getHistoricUri: api/v1/weather/history/city/{city}/prediction/{prediction}
   getPredictionUri: api/v1/weather/{city}

dependencies:
   weatherServicePort: ${MINUTEMAN_WEATHER_SERVICE_PORT:8090}
   weatherServiceId: ${MINUTEMAN_WEATHER_SERVICE_ID:}

dcos-cluster:
  domain: ${MINUTEMAN_DOMAIN:localhost}
  port: ${MINUTEMAN_API_WEATHER_PORT:8092}